branches:
  only:
    - hexo

language: node_js
node_js:
  - lts/*
cache:
  directories:
    - node_modules

install:
  - npm install
script:
  - npm run ${SCRIPT}
deploy:
  provider: pages
  on:
    branch: hexo
  fqdn: hop-on-hop-off-chengdu.com
  skip_cleanup: true
  local_dir: ${FOLDER}
  token: ${TOKEN}
  target_branch: ${BRANCH}